import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import { ThemeProvider } from "@/app/Components/theme-provider";
import Nav from "./Components/Nav";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"]
  , weight: ["100", "200"]
  , style: ["normal", "italic"]
})


export const metadata = {
  title: "Sluch Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} antialiased scroll-smooth`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
          <Nav/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
